# Generated by Django 4.2.19 on 2025-02-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_collection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='gear.library'),
        ),
    ]
