# Generated by Django 4.2.19 on 2025-02-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_alter_collection_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(default='item_images/default_gear.png', upload_to='item_images/'),
        ),
    ]
