# Generated by Django 4.2.19 on 2025-02-21 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0005_alter_collection_image_alter_itemimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='librarians',
        ),
    ]
