# Generated by Django 4.2.19 on 2025-02-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_remove_library_librarians'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.png', null=True, upload_to='item_images/'),
        ),
    ]
