# Generated by Django 4.2.19 on 2025-02-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0007_library_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.jpg', null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.jpg', null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.jpg', null=True, upload_to='item_images/'),
        ),
    ]
