# Generated by Django 4.2.19 on 2025-02-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0008_alter_collection_image_alter_itemimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='name',
            new_name='title',
        ),
    ]
