# Generated by Django 4.2.19 on 2025-03-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0009_rename_name_library_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
