# Generated by Django 4.2.19 on 2025-04-09 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_profile_picture'),
        ('gear', '0012_alter_collection_image_alter_itemimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='users.userprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='gear.item')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_requests', to='users.userprofile')),
            ],
        ),
    ]
