# Generated by Django 4.2.19 on 2025-04-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0013_rentalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
