# Generated by Django 4.2.19 on 2025-04-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0015_collectionaccessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='library',
        ),
        migrations.AddField(
            model_name='collection',
            name='libraries',
            field=models.ManyToManyField(blank=True, related_name='collections', to='gear.library'),
        ),
    ]
