# Generated by Django 4.2.19 on 2025-04-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0017_itemreview_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.png', upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(blank=True, default='item_images/default_gear.png', upload_to='item_images/'),
        ),
    ]
