# Generated by Django 4.2.19 on 2025-04-29 02:18

from django.db import migrations
import gear.models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0018_alter_collection_image_alter_library_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=gear.models.ProtectedImageField(blank=True, default='item_images/default_gear.png', upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=gear.models.ProtectedImageField(blank=True, default='item_images/default_gear.png', null=True, upload_to='item_images/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=gear.models.ProtectedImageField(blank=True, default='item_images/default_gear.png', upload_to='item_images/'),
        ),
    ]
