# Generated by Django 4.2.19 on 2025-04-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_collection_requests',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_rental_requests',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
